server:
  port: 7000
spring:
  application:
    name:  jpa-app

  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:mem:h2test;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE # H2不开启控制台
    #url: jdbc:h2:~/testdb # 开启控制台写法
    username: ud # H2不能设置和管理台一样
    password: ud123
    hikari:
      maximum-pool-size: 10  # 最大连接数
      minimum-idle: 5 # 最小空闲数
      connection-timeout: 2000 # 获取连接超时时间； 默认30s
      pool-name: hikari # 连接池名称
      idle-timeout: 600000 # 空闲超时时间；默认是十分钟；空闲时间超过设定时间则会被回收
      auto-commit: true # 是否自动提交
      max-lifetime: 1800000 # 最大存活时间，默认30分钟
      connection-test-query: SELECT 1  # 连接数据库后测试语句
      validation-timeout: 1000 #
      # schema: 设置模式，例如 postgresql 有模式这个概念
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    database: h2 # h2数据库
    open-in-view: true
  h2:
    console:
      enabled: false  #h2数据库控制台 ,windows上无法在~/下创建，所以连不上
      settings:
        web-admin-password: ud123
        trace: false
        web-allow-others: false
      path: /h2-console